Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "backdoored-host"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.name = "usaf-backdoored-host"
  end

  config.vm.synced_folder "../../shared", "/vagrant/shared"
  config.vm.provision "shell", path: "provision.sh"
end
